### ISSUE TITLE
Array riordinato decrescente e crescente

### ISSUE THREAD

**Issue by Lomba0job** [Lomba0job/Esercitazione_c#5]

**Comment by RED-ITA** [comment]
Creare tre array di dimensione variabile in base alla richiesta iniziale. 
riempire il primo array da tastiera, con numeri casuali 
riordinare i valori del primo array in ordine crescente salvandoli sul secondo 
riordinare i valori del primo array in ordine decrescente salvandoli sul terzo

Ottenere un OUTPUT composoto così:


Quanti valori si volgiono riordinare: 4

inserire il valore n1: 1
inserire il valore n2: 5
inserire il valore n3: 3
inserire il valore n4: 4


array principale:   1 5 3 4
array crescente:    1 3 4 5
array decrescente:  5 4 3 1
